advancement revoke @s only is:powers/aquatic_breathing
advancement revoke @s only is:powers/burning_ray
advancement revoke @s only is:powers/depth_scan
advancement revoke @s only is:powers/ender_look
advancement revoke @s only is:powers/explo_beam
advancement revoke @s only is:powers/explosive_ball
advancement revoke @s only is:powers/extinguisher
advancement revoke @s only is:powers/fire_launcher
advancement revoke @s only is:powers/flash_move
advancement revoke @s only is:powers/giant_leap
advancement revoke @s only is:powers/glacial_wave
advancement revoke @s only is:powers/health_halo
advancement revoke @s only is:powers/health_regen
advancement revoke @s only is:powers/ice_trap
advancement revoke @s only is:powers/icy_aura
advancement revoke @s only is:powers/icy_throw
advancement revoke @s only is:powers/instant_invulnerability
advancement revoke @s only is:powers/item_attractor
advancement revoke @s only is:powers/lightning
advancement revoke @s only is:powers/meteor_strike
advancement revoke @s only is:powers/projectile_barrier
advancement revoke @s only is:powers/shock_wave
advancement revoke @s only is:powers/sparkling_ray
advancement revoke @s only is:powers/storm_invoker
advancement revoke @s only is:powers/strip_miner
advancement revoke @s only is:powers/telekinesis
advancement revoke @s only is:powers/vertical_ascend
advancement revoke @s only is:powers/volley_arrow
